//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoeduSam
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductsSales
    {
        public int Id { get; set; }
        public string Product { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> Kolichestvo { get; set; }
        public Nullable<System.DateTime> DateSale { get; set; }
    
        public virtual Products Products { get; set; }
    }
}
